version: '3'
services:
  web:
    build: nginx
    volumes:
      - "./nginx/conf.d/:/etc/nginx/conf.d/"
      - "../:/var/www/html"
    ports:
      - "80:80"
    depends_on:
      - php
      - db
  php:
    build: php
    restart: always
    volumes:
      - "./php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "../:/var/www/html"
  db:
    build: mysql
    restart: always
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - "./mysql/data:/var/lib/mysql"
